### PR TITLE
Fix formParameters details

### PR DESCRIPTION
**Pull request by vbarashkov**
Get all properties from model and show in schema

### CODE REVIEW

**Comment by supermitsuba** [comment]
Awesome!  Thanks for supporting the project!  There is one thing I would ask, and that is we add unit tests around the new code that was added.  I would write them, but I am a bit swamped with other things.  Once we have some unit tests, I can merge the changes, no problem.

**Comment by vbarashkov** [comment]
Thank you!

**Comment by vbarashkov** [comment]
Little change request in Schema. You can set Type of object and Json.Net make response dto with property info. It's very usefully for our project.

**Comment by supermitsuba** [comment]
Ill go ahead then and merge it.  Deploy a nuget package.  Ill circle back and test it later.

**Pull request merged**
